import type { MenuPermissionListItem } from 'src/types/menu-permission';

// ----------------------------------------------------------------------

/** Sample payload shape from permission settings get-list API */
export const _menuPermissionList: MenuPermissionListItem[] = [
  { menuID: 1, menuName: 'Project', isReport: false },
  { menuID: 2, menuName: 'Task', isReport: false },
  { menuID: 3, menuName: 'Discussions', isReport: false },
  { menuID: 4, menuName: 'Timesheet', isReport: false },
  { menuID: 5, menuName: 'Activity', isReport: false },
  { menuID: 6, menuName: 'Notes', isReport: false },
  { menuID: 7, menuName: 'Expenses', isReport: false },
  { menuID: 8, menuName: 'Invoice', isReport: false },
  { menuID: 9, menuName: 'Estimate', isReport: false },
  { menuID: 10, menuName: 'My Work', isReport: false },
  { menuID: 11, menuName: 'Workload', isReport: false },
  { menuID: 12, menuName: 'Calendar', isReport: false },
  { menuID: 13, menuName: 'People', isReport: false },
  { menuID: 14, menuName: 'Department', isReport: false },
  { menuID: 15, menuName: 'Department Team', isReport: false },
  { menuID: 16, menuName: 'Custome Fields', isReport: false },
  { menuID: 17, menuName: 'Trash', isReport: false },
  { menuID: 18, menuName: 'Settings', isReport: false },
  { menuID: 21, menuName: 'Expenses', isReport: true },
  { menuID: 26, menuName: 'Project Budget Vs Actual', isReport: true },
  { menuID: 10033, menuName: 'Team', isReport: false },
  { menuID: 19, menuName: 'Reports', isReport: false },
  { menuID: 27, menuName: 'Dashboard', isReport: false },
  { menuID: 40, menuName: 'Client Company', isReport: false },
  { menuID: 28, menuName: 'File Manager', isReport: false },
  { menuID: 29, menuName: 'Task Automation', isReport: false },
  { menuID: 20, menuName: 'Timesheet', isReport: true },
  { menuID: 22, menuName: 'Projects', isReport: true },
  { menuID: 23, menuName: 'Invoice', isReport: true },
  { menuID: 24, menuName: 'Estimate', isReport: true },
  { menuID: 25, menuName: 'Tasks', isReport: true },
  { menuID: 41, menuName: 'Recurring Project', isReport: false },
  { menuID: 10034, menuName: 'Timesheet_MultiSelect', isReport: true },
  { menuID: 45, menuName: 'Activity', isReport: true },
  { menuID: 46, menuName: 'Project Planning', isReport: true },
  { menuID: 50, menuName: 'User Allocation', isReport: true },
  { menuID: 51, menuName: 'Project Allocation', isReport: true },
  { menuID: 49, menuName: 'Timesheet Summary', isReport: true },
  { menuID: 10028, menuName: 'Task Aging', isReport: true },
  { menuID: 64, menuName: 'Others', isReport: false },
  { menuID: 63, menuName: 'ProjectReview', isReport: false },
  { menuID: 62, menuName: 'WorkHours', isReport: false },
  { menuID: 61, menuName: 'Invoice', isReport: false },
  { menuID: 60, menuName: 'JOFList', isReport: false },
  { menuID: 10031, menuName: 'ProjectOverview', isReport: false },
  { menuID: 10032, menuName: 'Template', isReport: false },
  { menuID: 10029, menuName: 'Task Budget Vs Actual', isReport: true },
  { menuID: 10030, menuName: 'Timesheet Gaps Summary', isReport: true },
  { menuID: 10035, menuName: 'Timesheet Summary_MultiSelect', isReport: true },
  { menuID: 10036, menuName: 'Project Budget Vs Actual_MultiSelect', isReport: true },
  { menuID: 10037, menuName: 'Task Budget Vs Actual_MultiSelect', isReport: true },
];
